FROM node:14-alpine AS build
WORKDIR /home/fshinkae/trybe-exercicios/03-Back-End/bloco-19-docker-utilizando-container/dia-19.3-orquestrando-containers-com-docker-compose/Exercicio 5/react-dockerized
CMD ["npm", "start"]